[versions]
kotlin = "1.7.20"
gradle-plugin = "7.4.1"
hilt = "2.44"
lifecycle = "2.5.1"
coroutines = "1.6.4"
androidx-appcompat = "1.5.1"
material = "1.7.0"
glide = "4.12.0"

[libraries]
koltin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
koltin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-extensions = "androidx.lifecycle:lifecycle-extensions:2.2.0"

material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-legacy = "androidx.legacy:legacy-support-v4:1.0.0"
androidx-multidex = "androidx.multidex:multidex:2.0.1"

fragment-ktx = "androidx.fragment:fragment-ktx:1.5.3"
preference-ktx = "androidx.preference:preference-ktx:1.2.0"
palette-ktx = "androidx.palette:palette-ktx:1.0.0"

constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
cardview = "androidx.cardview:cardview:1.0.0"
mp-chart = "com.github.PhilJay:MPAndroidChart:v3.1.0-alpha"
gif-drawable = "pl.droidsonroids.gif:android-gif-drawable:1.2.10"
highlightjs = "com.pddstudio:highlightjs-android:1.5.0"
appintro = "com.github.AppIntro:AppIntro:6.1.0"
expandablelayout = "net.cachapa.expandablelayout:expandablelayout:2.9.2"
timber = "com.jakewharton.timber:timber:5.0.1"
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

google-play-core = "com.google.android.play:core:1.10.3"
google-play-core-ktx = "com.google.android.play:core-ktx:1.8.1"

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

firebase-bom = "com.google.firebase:firebase-bom:27.0.0"

leakcannary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
junit = "junit:junit:4.13.2"
espresso-core = "androidx.test.espresso:espresso-core:3.1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
crashlytics = "com.google.firebase.crashlytics:2.9.2"
firebase-perf = "com.google.firebase.firebase-perf:1.4.2"
google-services = "com.google.gms.google-services:4.3.14"
spotless = "com.diffplug.spotless:6.16.0"

[bundles]
lifecycle = ["lifecycle-livedata-ktx", "lifecycle-viewmodel-ktx", "lifecycle-common-java8", "lifecycle-extensions"]
google-play = ["google-play-core", "google-play-core-ktx"]